version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    # Executor is the environment in which my job is running
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test